name: csharp CI

on:
  push:
    branches: [ csharp ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore csharp/rebisco-bugtracker.Tests/rebisco-bugtracker.Tests.csproj
        
      - name: Build
        run: dotnet build csharp/rebisco-bugtracker.Tests/rebisco-bugtracker.Tests.csproj --no-restore

      - name: Test
        run: dotnet test csharp/rebisco-bugtracker.Tests/rebisco-bugtracker.Tests.csproj --no-build --collect:"XPlat Code Coverage"


